### ISSUE TITLE
Torch7 libjpeg missing?

### ISSUE THREAD

**Issue by hzh8311** [ufoym/deepo#24]
When using the torch  and loading images, it reports libjpeg not found. 
## Reproduce
$ th
> require('image')
> image.lena() or image.load('xxxx.jpg')

## Output
```
/usr/local/share/lua/5.1/trepl/init.lua:389: module 'libjpeg' not found:No LuaRocks module found for libjpeg
	no field package.preload['libjpeg']
	no file '/root/.luarocks/share/lua/5.1/libjpeg.lua'
	no file '/root/.luarocks/share/lua/5.1/libjpeg/init.lua'
	no file '/usr/local/share/lua/5.1/libjpeg.lua'
	no file '/usr/local/share/lua/5.1/libjpeg/init.lua'
	no file './libjpeg.lua'
	no file '/usr/local/share/luajit-2.1.0-beta1/libjpeg.lua'
	no file '/.luarocks/share/lua/5.1/libjpeg.lua'
	no file '/.luarocks/share/lua/5.1/libjpeg/init.lua'
	no file '/root/.luarocks/lib/lua/5.1/libjpeg.so'
	no file '/usr/local/lib/lua/5.1/libjpeg.so'
	no file './libjpeg.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/.luarocks/lib/lua/5.1/libjpeg.so'	
warning: <libjpeg> could not be loaded (is it installed?)	
/usr/local/share/lua/5.1/trepl/init.lua:389: module 'liblua_png' not found:No LuaRocks module found for liblua_png
	no field package.preload['liblua_png']
	no file '/root/.luarocks/share/lua/5.1/liblua_png.lua'
	no file '/root/.luarocks/share/lua/5.1/liblua_png/init.lua'
	no file '/usr/local/share/lua/5.1/liblua_png.lua'
	no file '/usr/local/share/lua/5.1/liblua_png/init.lua'
	no file './liblua_png.lua'
	no file '/usr/local/share/luajit-2.1.0-beta1/liblua_png.lua'
	no file '/.luarocks/share/lua/5.1/liblua_png.lua'
	no file '/.luarocks/share/lua/5.1/liblua_png/init.lua'
	no file '/root/.luarocks/lib/lua/5.1/liblua_png.so'
	no file '/usr/local/lib/lua/5.1/liblua_png.so'
	no file './liblua_png.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/.luarocks/lib/lua/5.1/liblua_png.so'	
warning: <liblua_png> could not be loaded (is it installed?)	
/usr/local/share/lua/5.1/dok/inline.lua:738: <image.lena> no bindings available to load images (libjpeg AND libpng missing)
stack traceback:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/dok/inline.lua:738: in function 'error'
	/usr/local/share/lua/5.1/image/init.lua:1690: in function 'lena'
	[string "_RESULT={image.lena()}"]:1: in main chunk
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/trepl/init.lua:661: in function 'repl'
	/usr/local/lib/luarocks/rocks/trepl/scm-1/bin/th:204: in main chunk
	[C]: at 0x00405050	
```

Is it  a docker image bug or a OS-related library missing? How do I fix it?

**Comment by ufoym** [comment]
Thank you for reporting this issue. We have just fixed it. New docker images will be available in a few hours.

**Comment by hzh8311** [comment]
Since  I can only use cuda8-cudnn7 on our server,  I start a container based on deepo (cuda8-cudnn7 version) and  install the two missing libraries. But it shows that the two libraries are already installed, yet the problem is still occured when I used `image.lena()`  in the container. Any advise about this problem?
